import { uiCss } from './ui-css';
import { uiScript } from './ui-script';

export const appHtml = `<!doctype html>
<html lang="ru" data-theme="dark">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Cue — configurable Telegram reminders, schedules and checklists."><meta name="theme-color" content="#0d0e10"><title>Cue</title><style>${uiCss}</style></head>
<body><div class="app">
  <aside class="sidebar" id="sidebar">
    <div class="brand"><span class="brand-mark" aria-label="Cue"><i></i></span><span class="brand-copy">Cue<small data-i18n="brandTagline">Reminder builder</small></span></div>
    <div class="nav-label" data-i18n="workspace">Workspace</div>
    <button class="nav-item active" data-view="dashboard" data-title-key="dashboard"><span class="nav-icon">⌂</span><span data-i18n="dashboard">Dashboard</span></button>
    <button class="nav-item" data-view="reminders" data-title-key="reminders"><span class="nav-icon">◉</span><span data-i18n="reminders">Reminders</span></button>
    <button class="nav-item" data-view="runs" data-title-key="runs"><span class="nav-icon">▷</span><span data-i18n="runs">Runs & checklist</span></button>
    <button class="nav-item" data-view="clients" data-title-key="clients"><span class="nav-icon">◎</span><span data-i18n="clients">Clients</span></button>
    <button class="nav-item" data-view="messages" data-title-key="messages"><span class="nav-icon">▤</span><span data-i18n="messages">Messages</span></button>
    <button class="nav-item" data-view="aliases" data-title-key="aliases"><span class="nav-icon">{ }</span><span data-i18n="aliases">Aliases</span></button>
    <div class="nav-label" data-i18n="automation">Automation</div>
    <button class="nav-item" data-view="conditions" data-title-key="conditions"><span class="nav-icon">◇</span><span data-i18n="conditions">Conditions</span></button>
    <button class="nav-item" data-view="work" data-title-key="workSchedules"><span class="nav-icon">◷</span><span data-i18n="workSchedules">Work schedules</span></button>
    <button class="nav-item" data-view="deliveries" data-title-key="deliveries"><span class="nav-icon">↗</span><span data-i18n="deliveries">Deliveries</span></button>
    <div class="nav-label" data-i18n="system">System</div>
    <button class="nav-item" data-view="settings" data-title-key="settings"><span class="nav-icon">⚙︎</span><span data-i18n="settings">Settings</span></button>
  </aside>
  <div class="content"><header class="topbar"><div class="actions"><button class="mobile-menu" id="mobileMenu" aria-label="Menu">☰</button><span class="crumb">Cue / <b id="currentTitle">Dashboard</b></span></div><div class="top-actions"><div class="language-switch" aria-label="Language"><button id="langRu">RU</button><button id="langEn">EN</button></div><button class="icon-button" id="themeToggle" aria-label="Theme"><span class="theme-icon">☼</span></button><div class="top-status"><span class="status-dot" id="topStatusDot"></span><span id="topStatusText">Setup required</span></div></div></header>
    <main class="main">
      <section class="view" id="dashboard"><div class="page-head"><div><h1 class="page-title" data-i18n="dashboard">Dashboard</h1><p class="page-description" data-i18n="dashboardDescription">A clear view of reminders, recipients and work still in progress.</p></div><button class="btn primary" data-go="reminders" id="dashboardNewReminder">＋ <span data-i18n="newReminder">New reminder</span></button></div>
        <div class="grid stats"><div class="card stat-card"><div class="stat-icon">◉</div><div><div class="stat-label" data-i18n="activeReminders">Active reminders</div><div class="stat-value" id="statReminders">—</div><div class="stat-foot" data-i18n="enabledDefinitions">Enabled definitions</div></div></div><div class="card stat-card"><div class="stat-icon">◎</div><div><div class="stat-label" data-i18n="activeClients">Active clients</div><div class="stat-value" id="statClients">—</div><div class="stat-foot" data-i18n="telegramRecipients">Telegram recipients</div></div></div><div class="card stat-card"><div class="stat-icon">✓</div><div><div class="stat-label" data-i18n="pendingChecklist">Pending checklist</div><div class="stat-value" id="statPending">—</div><div class="stat-foot" data-i18n="itemsStillOpen">Items still open</div></div></div><div class="card stat-card"><div class="stat-icon">▷</div><div><div class="stat-label" data-i18n="activeRuns">Active runs</div><div class="stat-value" id="statRuns">—</div><div class="stat-foot" data-i18n="currentPeriods">Current periods</div></div></div></div>
        <div class="grid two dashboard-grid"><div class="card"><div class="section-head"><div><h2 data-i18n="runtimeReadiness">Runtime readiness</h2><p class="card-subtitle" data-i18n="runtimeHint">Hosted configuration required for delivery.</p></div></div><div class="readiness" id="runtimeReadiness"></div></div><div class="card"><div class="section-head"><div><h2 data-i18n="quickSetup">Quick setup</h2><p class="card-subtitle" data-i18n="quickSetupHint">Three reusable building blocks, no scenario-specific presets.</p></div></div><div class="quick-grid"><button class="quick-tile" data-go="clients"><span>◎</span><b data-i18n="addClients">Add clients</b><small data-i18n="addClientsHint">Recipients and chat IDs</small></button><button class="quick-tile" data-go="messages"><span>▤</span><b data-i18n="createMessage">Create a message</b><small data-i18n="createMessageHint">Text, aliases and controls</small></button><button class="quick-tile" data-go="reminders"><span>◉</span><b data-i18n="configureReminder">Configure reminder</b><small data-i18n="configureReminderHint">Schedule, recipients and rules</small></button></div></div></div>
      </section>

      <section class="view hidden" id="reminders"><div class="page-head"><div><h1 class="page-title" data-i18n="reminders">Reminders</h1><p class="page-description" data-i18n="remindersDescription">Choose when to send and separately decide whether completion should be tracked.</p></div><button class="btn primary" id="newReminder">＋ <span data-i18n="newReminder">New reminder</span></button></div>
        <div class="card editor-card" id="reminderEditor"><div class="section-head"><div><h2 id="remEditorTitle" data-i18n="newReminder">New reminder</h2><p class="card-subtitle" data-i18n="reminderEditorHint">Four short steps instead of one long form.</p></div></div>
          <nav class="wizard-stepper" aria-label="Reminder setup"><button data-rem-step="0" class="active"><span>1</span><b data-i18n="stepBasics">Basics</b></button><i></i><button data-rem-step="1"><span>2</span><b data-i18n="stepSchedule">Schedule</b></button><i></i><button data-rem-step="2"><span>3</span><b data-i18n="stepRecipients">Recipients</b></button><i></i><button data-rem-step="3"><span>4</span><b data-i18n="stepBehavior">Behavior</b></button></nav>
          <div class="editor-layout"><div class="editor-main">
            <section class="wizard-panel" data-rem-panel="0"><div class="step-heading"><span>01</span><div><h3 data-i18n="stepBasics">Basics</h3><p data-i18n="stepBasicsHint">What to send and how important it is.</p></div></div><div class="distinction-callout"><strong data-i18n="scheduleType">Schedule type</strong><span data-i18n="scheduleTypeHint">This only defines when the reminder runs. Completion tracking is configured later.</span></div><div class="type-cards two" id="remTypeCards"><label><input type="radio" name="remType" value="once"><span><b data-i18n="typeOnce">One-time</b><small data-i18n="typeOnceHint">Runs once on a selected date</small></span></label><label><input type="radio" name="remType" value="recurring" checked><span><b data-i18n="typeRecurring">Recurring</b><small data-i18n="typeRecurringHint">Repeats on selected weekdays</small></span></label></div><div class="form-grid three"><div class="field span-2"><label data-i18n="name">Name</label><input id="remName" data-i18n-placeholder="reminderNamePlaceholder"></div><div class="field"><label data-i18n="priority">Priority</label><select id="remPriority"><option value="low">Low</option><option value="normal" selected>Normal</option><option value="high">High</option><option value="critical">Critical</option></select></div></div><div class="field"><label data-i18n="description">Description</label><textarea id="remDescription" data-i18n-placeholder="descriptionPlaceholder"></textarea></div><div class="form-grid two"><div class="field"><label data-i18n="message">Message</label><div class="relation-field"><select id="remTemplate"></select><button class="btn icon" id="createMessageInline" title="Create message">＋</button></div></div><div class="field"><label data-i18n="workSchedule">Work schedule</label><div class="relation-field"><select id="remWork"></select><button class="btn icon" id="createWorkInline" title="Create schedule">＋</button></div></div></div></section>
            <section class="wizard-panel hidden" data-rem-panel="1"><div class="step-heading"><span>02</span><div><h3 data-i18n="stepSchedule">Schedule</h3><p data-i18n="stepScheduleHint">Select days, active hours and repeat interval.</p></div></div><div class="form-grid two"><div class="field only-once"><label data-i18n="runDate">Run date</label><input id="remDate" type="date"></div><div class="field"><label data-i18n="timezone">Timezone</label><input id="remTimezone" value="Asia/Qyzylorda"></div></div><div class="only-recurring"><div class="section-row"><span class="field-label" data-i18n="activeWeekdays">Active weekdays</span><div class="segmented" id="dayPresets"><button data-day-preset="workdays" data-i18n="workdays">Workdays</button><button data-day-preset="all" data-i18n="everyDay">Every day</button><button data-day-preset="weekends" data-i18n="weekends">Weekends</button><button data-day-preset="custom" data-i18n="custom">Custom</button></div></div><div class="day-checks" id="remDays"></div></div><div class="time-section only-scheduled"><div class="section-row"><div><span class="field-label" data-i18n="activeWindow">Active window</span><p class="field-hint" data-i18n="activeWindowHint">Drag the wheels or use the arrows.</p></div><label class="switchline"><input type="checkbox" id="remAllDay"><span></span><em data-i18n="allDay">All day</em></label></div><div class="time-wheel-grid" id="remTimeWindow"><div class="time-field"><label data-i18n="start">Start</label><div id="remStartWheel"></div></div><div class="time-field"><label data-i18n="stop">Stop</label><div id="remStopWheel"></div></div></div></div><div class="repeat-section only-repeat"><span class="field-label" data-i18n="repeat">Repeat</span><p class="field-hint" data-i18n="repeatHint">At least 10 minutes. Combine hours and minutes without mental arithmetic.</p><div class="duration-composer"><button class="duration-step" data-repeat-adjust="-10">−</button><div class="duration-unit"><input id="repeatHours" type="number" min="0" max="168" value="0"><span data-i18n="hours">hours</span></div><span class="duration-colon">:</span><div class="duration-unit"><input id="repeatMinutes" type="number" min="0" max="59" step="10" value="30"><span data-i18n="minutes">minutes</span></div><button class="duration-step" data-repeat-adjust="10">＋</button><strong id="repeatSummary">30 min</strong></div><div class="quick-values"><button data-repeat-total="10">10m</button><button data-repeat-total="30">30m</button><button data-repeat-total="60">1h</button><button data-repeat-total="120">2h</button></div></div></section>
            <section class="wizard-panel hidden" data-rem-panel="2"><div class="step-heading"><span>03</span><div><h3 data-i18n="stepRecipients">Recipients</h3><p data-i18n="stepRecipientsHint">Find people, filter the list or select everyone.</p></div></div><div class="recipients-section no-border"><div class="section-row"><div><span class="field-label" data-i18n="recipients">Recipients</span><p class="field-hint"><span id="recipientCount">0</span> <span data-i18n="selected">selected</span></p></div><div class="actions"><button class="btn small" id="selectAllRecipients" data-i18n="selectAll">Select all</button><button class="btn small ghost" id="clearRecipients" data-i18n="clear">Clear</button></div></div><div class="list-toolbar compact"><label class="searchbox"><span>⌕</span><input id="recipientSearch" data-i18n-placeholder="searchRecipients"></label><select id="recipientFilter"><option value="all" data-i18n="all">All</option><option value="active" data-i18n="active">Active</option><option value="inactive" data-i18n="inactive">Inactive</option></select></div><div class="recipient-grid" id="remTargets"></div><div class="pager" id="recipientPager"></div></div></section>
            <section class="wizard-panel hidden" data-rem-panel="3"><div class="step-heading"><span>04</span><div><h3 data-i18n="stepBehavior">Behavior</h3><p data-i18n="stepBehaviorHint">Decide whether Cue should only notify or also track completion.</p></div></div><div class="behavior-cards"><label><input type="radio" name="remBehavior" value="notify" checked><span><b data-i18n="behaviorNotify">Send notifications</b><small data-i18n="behaviorNotifyHint">Send on the selected schedule without a checklist.</small></span></label><label><input type="radio" name="remBehavior" value="track"><span><b data-i18n="behaviorTrack">Track completion</b><small data-i18n="behaviorTrackHint">Create a checklist and remind only people who are not done.</small></span></label></div><input type="checkbox" id="remChecklist" class="hidden"><div class="form-grid two option-grid"><label class="option-row"><input type="checkbox" id="remUseRule" checked><span><b data-i18n="useConditions">Use conditions</b><small data-i18n="conditionsHint">Apply the current WHEN / THEN rule</small></span></label><label class="option-row"><input type="checkbox" id="remEnabled" checked><span><b data-i18n="enabled">Enabled</b><small data-i18n="enabledHint">Scheduler may start this reminder</small></span></label></div><div class="pause-section"><div class="section-head"><div><h2 data-i18n="recurringPauses">Pauses</h2><p class="card-subtitle" data-i18n="pausesHint">Pause by weekday, exact date or date range.</p></div><button class="btn small" id="addPauseRule">＋ <span data-i18n="addPause">Add pause</span></button></div><div class="pause-cards" id="pauseRules"></div></div></section>
          </div><aside class="editor-side"><div class="side-panel wizard-help"><span id="wizardStepNumber">1 / 4</span><h3 id="wizardStepTitle" data-i18n="stepBasics">Basics</h3><p id="wizardStepHint" data-i18n="stepBasicsHint">What to send and how important it is.</p></div><div class="side-panel summary-panel"><h3 data-i18n="summary">Summary</h3><div id="reminderSummary"></div></div></aside></div>
          <div class="wizard-nav"><button class="btn ghost" id="cancelReminder" data-i18n="reset">Reset</button><div class="actions"><button class="btn ghost hidden" id="remWizardBack">← <span data-i18n="back">Back</span></button><button class="btn primary" id="remWizardNext"><span data-i18n="next">Next</span> →</button><button class="btn primary hidden" id="saveReminder" data-i18n="saveReminder">Save reminder</button></div></div></div>
        <div class="card"><div class="section-head"><div><h2 data-i18n="savedReminders">Saved reminders</h2><p class="card-subtitle" data-i18n="savedRemindersHint">Search, filter and open any definition.</p></div></div><div class="list-toolbar"><label class="searchbox"><span>⌕</span><input id="reminderSearch" data-i18n-placeholder="search"></label><select id="reminderFilter"><option value="all" data-i18n="all">All</option><option value="enabled" data-i18n="enabled">Enabled</option><option value="disabled" data-i18n="disabled">Disabled</option><option value="once" data-i18n="typeOnce">One-time</option><option value="recurring" data-i18n="typeRecurring">Recurring</option></select></div><div class="table-wrap"><table class="table"><thead><tr><th data-i18n="name">Name</th><th data-i18n="type">Type</th><th data-i18n="priority">Priority</th><th data-i18n="schedule">Schedule</th><th data-i18n="status">Status</th><th></th></tr></thead><tbody id="reminderRows"></tbody></table></div><div class="pager" id="reminderPager"></div></div>
      </section>

      <section class="view hidden" id="runs"><div class="page-head"><div><h1 class="page-title" data-i18n="runs">Runs & checklist</h1><p class="page-description" data-i18n="runsDescription">Operational periods, pauses and checklist progress.</p></div><button class="btn" id="refreshRuns">↻ <span data-i18n="refresh">Refresh</span></button></div><div class="list-toolbar"><label class="searchbox"><span>⌕</span><input id="runSearch" data-i18n-placeholder="search"></label><select id="runFilter"><option value="all" data-i18n="all">All</option><option value="active" data-i18n="active">Active</option><option value="completed" data-i18n="completed">Completed</option><option value="stopped" data-i18n="stopped">Stopped</option></select></div><div class="grid" id="runCards"></div><div class="pager" id="runPager"></div></section>

      <section class="view hidden" id="clients"><div class="page-head"><div><h1 class="page-title" data-i18n="clients">Clients</h1><p class="page-description" data-i18n="clientsDescription">Telegram recipients with tags and fields for conditions.</p></div><button class="btn primary" id="newClient">＋ <span data-i18n="newClient">New client</span></button></div><div class="card editor-card"><div class="section-head"><div><h2 id="clientEditorTitle" data-i18n="newClient">New client</h2><p class="card-subtitle" data-i18n="clientEditorHint">Identity and delivery settings fit in one compact grid.</p></div></div><div class="form-grid three"><div class="field"><label data-i18n="displayName">Display name</label><input id="clientName"></div><div class="field"><label data-i18n="telegramChatId">Telegram chat ID</label><input id="clientChat"></div><div class="field"><label data-i18n="telegramUserId">Telegram user ID</label><input id="clientUser"></div><div class="field"><label data-i18n="timezone">Timezone</label><input id="clientTimezone"></div><div class="field span-2"><label data-i18n="tags">Tags</label><input id="clientTags"></div><div class="field span-2"><label data-i18n="customFields">Custom fields</label><textarea id="clientCustom" placeholder='{"department":"Engineering"}'></textarea></div><label class="option-row compact-option"><input type="checkbox" id="clientActive" checked><span><b data-i18n="activeRecipient">Active recipient</b></span></label></div><div class="form-actions"><button class="btn ghost" id="cancelClient" data-i18n="reset">Reset</button><button class="btn primary" id="saveClient" data-i18n="saveClient">Save client</button></div></div><div class="card"><div class="list-toolbar"><label class="searchbox"><span>⌕</span><input id="clientSearch" data-i18n-placeholder="search"></label><select id="clientFilter"><option value="all" data-i18n="all">All</option><option value="active" data-i18n="active">Active</option><option value="inactive" data-i18n="inactive">Inactive</option></select></div><div class="table-wrap"><table class="table"><thead><tr><th data-i18n="name">Name</th><th>Chat ID</th><th data-i18n="timezone">Timezone</th><th data-i18n="tags">Tags</th><th data-i18n="status">Status</th><th></th></tr></thead><tbody id="clientRows"></tbody></table></div><div class="pager" id="clientPager"></div></div></section>

      <section class="view hidden" id="messages"><div class="page-head"><div><h1 class="page-title" data-i18n="messages">Messages</h1><p class="page-description" data-i18n="messagesDescription">Reusable content with aliases and Telegram controls.</p></div><button class="btn primary" id="newTemplate">＋ <span data-i18n="newMessage">New message</span></button></div><div class="editor-layout"><div class="card"><div class="section-head"><h2 id="templateEditorTitle" data-i18n="newMessage">New message</h2></div><div class="form-grid two"><div class="field"><label data-i18n="name">Name</label><input id="templateName"></div><div class="field"><label>Parse mode</label><select id="templateParse"><option>HTML</option><option>Markdown</option><option>MarkdownV2</option></select></div></div><div class="field"><label data-i18n="messageText">Message text</label><textarea id="templateBody" class="message-editor"></textarea></div><div class="section-head"><h2 data-i18n="telegramControls">Telegram controls</h2><button class="btn small" id="addControl">＋ <span data-i18n="addControl">Add control</span></button></div><div class="list-editor" id="controlRows"></div><div class="form-actions"><button class="btn ghost" id="cancelTemplate" data-i18n="reset">Reset</button><button class="btn primary" id="saveTemplate" data-i18n="saveMessage">Save message</button></div></div><aside><div class="card sticky-card"><div class="section-head"><h2 data-i18n="preview">Preview</h2></div><div class="preview" id="messagePreview"></div></div></aside></div><div class="card"><div class="list-toolbar"><label class="searchbox"><span>⌕</span><input id="templateSearch" data-i18n-placeholder="search"></label><select id="templateFilter"><option value="all" data-i18n="all">All</option><option>HTML</option><option>Markdown</option><option>MarkdownV2</option></select></div><div class="card-grid" id="templateList"></div><div class="pager" id="templatePager"></div></div></section>

      <section class="view hidden" id="aliases"><div class="page-head"><div><h1 class="page-title" data-i18n="aliases">Aliases</h1><p class="page-description" data-i18n="aliasesDescription">Reusable values available in every message.</p></div></div><div class="card compact-form"><div class="form-grid three"><div class="field"><label data-i18n="alias">Alias</label><input id="aliasKey"></div><div class="field"><label data-i18n="value">Value</label><input id="aliasValue"></div><div class="field action-field"><button class="btn primary" id="saveAlias" data-i18n="saveAlias">Save alias</button></div></div></div><div class="card"><div class="list-toolbar"><label class="searchbox"><span>⌕</span><input id="aliasSearch" data-i18n-placeholder="search"></label><select id="aliasFilter"><option value="all" data-i18n="all">All</option><option value="global" data-i18n="global">Global</option></select></div><div class="table-wrap"><table class="table"><thead><tr><th data-i18n="placeholder">Placeholder</th><th data-i18n="value">Value</th><th></th></tr></thead><tbody id="aliasRows"></tbody></table></div><div class="pager" id="aliasPager"></div></div></section>

      <section class="view hidden" id="conditions"><div class="page-head"><div><h1 class="page-title" data-i18n="conditions">Conditions</h1><p class="page-description" data-i18n="conditionsDescription">Build reusable WHEN / THEN / ELSE behavior without JSON.</p></div><div class="actions"><button class="btn" id="addRootCondition">＋ <span data-i18n="condition">Condition</span></button><button class="btn" id="addRootGroup">＋ <span data-i18n="group">Group</span></button></div></div><div class="grid two"><div class="card"><div class="section-head"><h2>WHEN</h2></div><div class="rule-tree" id="conditionTree"></div><div class="divider"></div><div class="section-head"><h2>THEN</h2><button class="btn small" data-add-action="then">＋ <span data-i18n="action">Action</span></button></div><div class="list-editor" id="thenActions"></div><div class="divider"></div><div class="section-head"><h2>ELSE</h2><button class="btn small" data-add-action="else">＋ <span data-i18n="action">Action</span></button></div><div class="list-editor" id="elseActions"></div><div class="form-actions"><span class="muted" id="conditionValidity"></span><button class="btn primary" id="validateCondition" data-i18n="validateRule">Validate rule</button></div></div><div class="card"><div class="tabs"><button class="tab active" data-condition-tab="readable" data-i18n="readable">Readable</button><button class="tab" data-condition-tab="json">JSON</button></div><pre class="preview" id="conditionReadable"></pre><pre class="preview hidden" id="conditionJson"></pre></div></div></section>

      <section class="view hidden" id="work"><div class="page-head"><div><h1 class="page-title" data-i18n="workSchedules">Work schedules</h1><p class="page-description" data-i18n="workDescription">Reusable availability with half-hour precision and date exceptions.</p></div><button class="btn primary" id="newWork">＋ <span data-i18n="newSchedule">New schedule</span></button></div><div class="card"><div class="section-head"><h2 id="workEditorTitle" data-i18n="newSchedule">New schedule</h2></div><div class="form-grid three"><div class="field"><label data-i18n="name">Name</label><input id="workName"></div><div class="field"><label data-i18n="timezone">Timezone</label><input id="workTimezone"></div><label class="option-row compact-option"><input type="checkbox" id="workDefault"><span><b data-i18n="defaultSchedule">Default schedule</b></span></label></div><div class="schedule-toolbar"><select id="copyFrom"></select><span class="muted">→</span><select id="copyTo"></select><button class="btn small" id="copyDay" data-i18n="copyDay">Copy day</button><select id="clearDay"></select><button class="btn small" id="clearSelectedDay" data-i18n="clearDay">Clear day</button></div><div class="schedule-scroll"><div class="week-grid" id="weekGrid"></div></div><div class="divider"></div><div class="section-head"><h2 data-i18n="dateExceptions">Date exceptions</h2><button class="btn small" id="addException">＋ <span data-i18n="exception">Exception</span></button></div><div id="exceptionRows"></div><div class="form-actions"><button class="btn ghost" id="cancelWork" data-i18n="reset">Reset</button><button class="btn primary" id="saveWork" data-i18n="saveSchedule">Save schedule</button></div></div><div class="card"><div class="list-toolbar"><label class="searchbox"><span>⌕</span><input id="workSearch" data-i18n-placeholder="search"></label><select id="workFilter"><option value="all" data-i18n="all">All</option><option value="default" data-i18n="defaultSchedule">Default</option><option value="custom" data-i18n="custom">Custom</option></select></div><div class="table-wrap"><table class="table"><thead><tr><th data-i18n="name">Name</th><th data-i18n="timezone">Timezone</th><th data-i18n="type">Type</th><th></th></tr></thead><tbody id="workRows"></tbody></table></div><div class="pager" id="workPager"></div></div></section>

      <section class="view hidden" id="deliveries"><div class="page-head"><div><h1 class="page-title" data-i18n="deliveries">Deliveries</h1><p class="page-description" data-i18n="deliveriesDescription">Recent Telegram sends, failures and rendered messages.</p></div><button class="btn" id="refreshDeliveries">↻ <span data-i18n="refresh">Refresh</span></button></div><div class="card"><div class="list-toolbar"><label class="searchbox"><span>⌕</span><input id="deliverySearch" data-i18n-placeholder="search"></label><select id="deliveryFilter"><option value="all" data-i18n="all">All</option><option value="sent" data-i18n="sent">Sent</option><option value="failed" data-i18n="failed">Failed</option></select></div><div class="table-wrap"><table class="table"><thead><tr><th data-i18n="time">Time</th><th data-i18n="reminder">Reminder</th><th data-i18n="client">Client</th><th data-i18n="status">Status</th><th data-i18n="message">Message</th><th></th></tr></thead><tbody id="deliveryRows"></tbody></table></div><div class="pager" id="deliveryPager"></div></div></section>

      <section class="view hidden" id="settings"><div class="page-head"><div><h1 class="page-title" data-i18n="settings">Settings</h1><p class="page-description" data-i18n="settingsDescription">Bot identity, parse mode, timezone and Telegram commands.</p></div></div><div class="grid two"><div class="card"><div class="section-head"><h2 data-i18n="botConfiguration">Bot configuration</h2></div><div class="form-grid two"><div class="field"><label data-i18n="name">Name</label><input id="botName"></div><div class="field"><label>Username</label><input id="botUsername"></div><div class="field"><label>Parse mode</label><select id="botParse"><option>HTML</option><option>Markdown</option><option>MarkdownV2</option></select></div><div class="field"><label data-i18n="timezone">Timezone</label><input id="botTimezone"></div></div><label class="option-row compact-option"><input type="checkbox" id="botEnabled"><span><b data-i18n="botEnabled">Bot enabled</b></span></label><div class="divider"></div><div class="section-head"><h2 data-i18n="commands">Commands</h2><button class="btn small" id="addCommand">＋ <span data-i18n="command">Command</span></button></div><div class="list-editor" id="commandRows"></div><div class="form-actions"><button class="btn" id="syncCommands" data-i18n="syncTelegram">Sync to Telegram</button><button class="btn primary" id="saveBotConfig" data-i18n="saveSettings">Save settings</button></div></div><div class="card"><div class="section-head"><h2 data-i18n="deploymentStatus">Deployment status</h2></div><div class="readiness" id="settingsReadiness"></div><div class="callout"><strong data-i18n="privateDeployment">Private deployment</strong><br><span data-i18n="privateDeploymentHint">The admin interface remains owner-only. Public integrations require a separate protected surface.</span></div></div></div></section>
    </main>
  </div>
</div>
<dialog id="confirmDialog" class="confirm-dialog"><form method="dialog"><div class="confirm-icon">!</div><h2 data-i18n="confirmDelete">Delete item?</h2><p id="confirmMessage"></p><div class="form-actions"><button value="cancel" class="btn ghost" id="confirmCancel" data-i18n="cancel">Cancel</button><button value="confirm" class="btn danger solid" id="confirmAccept" data-i18n="delete">Delete</button></div></form></dialog><div class="toast hidden" id="toast"></div><script>${uiScript}</script></body></html>`;
