export const appHtml = String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cue</title>
<style>
:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#111827;background:#f5f7fb}*{box-sizing:border-box}body{margin:0}.layout{display:grid;grid-template-columns:240px 1fr;min-height:100vh}.side{background:#111827;color:#fff;padding:22px 16px}.brand{font-size:24px;font-weight:800;margin-bottom:24px}.side button{width:100%;text-align:left;background:transparent;color:#cbd5e1;border:0;padding:11px 12px;border-radius:10px;font-size:14px;cursor:pointer}.side button.active,.side button:hover{background:#1f2937;color:#fff}.main{padding:30px;max-width:1360px;width:100%;margin:auto}.top{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:20px}.h1{font-size:28px;font-weight:800}.muted{color:#6b7280}.btn{border:1px solid #d1d5db;background:#fff;padding:9px 13px;border-radius:9px;cursor:pointer}.btn.primary{background:#111827;color:#fff;border-color:#111827}.btn.danger{color:#b91c1c}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.two{display:grid;grid-template-columns:1fr 1fr;gap:14px}.three{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:18px;margin-bottom:16px}.stat{font-size:28px;font-weight:800;margin-top:8px}.hidden{display:none!important}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.field{display:grid;gap:6px;margin-bottom:12px}.field label{font-size:13px;font-weight:700}input,select,textarea{border:1px solid #d1d5db;border-radius:9px;padding:10px 11px;font:inherit;background:#fff;min-width:0}textarea{width:100%;min-height:110px}.checks{display:flex;gap:8px;flex-wrap:wrap}.checks label{border:1px solid #d1d5db;border-radius:8px;padding:7px 9px;font-size:13px}.rule{border:1px solid #dbe2ea;background:#f8fafc;border-radius:12px;padding:10px;margin:8px 0}.group{border-left:3px solid #111827;padding-left:12px;margin:10px 0}.pill{display:inline-block;border-radius:999px;background:#eef2ff;padding:4px 8px;font-size:12px}.ok{color:#047857}.bad{color:#b91c1c}.table{width:100%;border-collapse:collapse}.table td,.table th{padding:9px;border-bottom:1px solid #e5e7eb;text-align:left;font-size:13px;vertical-align:top}.preview{background:#111827;color:#e5e7eb;border-radius:12px;padding:14px;white-space:pre-wrap;min-height:120px;overflow:auto}.tabs{display:flex;gap:8px;margin-bottom:12px}.tabs button{border:0;background:#eef2f7;padding:8px 12px;border-radius:8px;cursor:pointer}.tabs button.active{background:#111827;color:#fff}.target-list{max-height:180px;overflow:auto;border:1px solid #e5e7eb;border-radius:10px;padding:8px}.target-list label{display:block;padding:6px}.section-title{font-size:17px;font-weight:800;margin-bottom:12px}@media(max-width:900px){.layout{grid-template-columns:1fr}.grid,.two,.three{grid-template-columns:1fr}.main{padding:18px}}
</style></head><body><div class="layout">
<aside class="side"><div class="brand">Cue</div><button data-view="dashboard" class="active">Dashboard</button><button data-view="reminders">Reminders</button><button data-view="runs">Runs & checklist</button><button data-view="clients">Clients</button><button data-view="templates">Messages</button><button data-view="aliases">Aliases</button><button data-view="conditions">Conditions</button><button data-view="settings">Settings</button></aside>
<main class="main">
<section id="dashboard" class="view"><div class="top"><div><div class="h1">Cue</div><div class="muted">Configurable Telegram reminder & workflow engine</div></div><button class="btn primary" id="seedTimesheet">Create timesheet preset</button></div><div class="grid"><div class="card"><div class="muted">Active reminders</div><div id="statReminders" class="stat">—</div></div><div class="card"><div class="muted">Clients</div><div id="statClients" class="stat">—</div></div><div class="card"><div class="muted">Pending checklist items</div><div id="statPending" class="stat">—</div></div></div><div class="card"><b>Execution model</b><p class="muted">Definition stores reusable configuration. Run is a concrete recurrence period with attempts, pause state, checklist and delivery history.</p></div></section>

<section id="reminders" class="view hidden"><div class="top"><div><div class="h1">Reminders</div><div class="muted">Schedule, recipients, pauses, priority, checklist and conditions.</div></div><button class="btn" id="refreshReminders">Refresh</button></div>
<div class="card"><div class="section-title">Create reminder</div><div class="three"><div class="field"><label>Name</label><input id="remName" placeholder="Weekly report"></div><div class="field"><label>Template</label><select id="remTemplate"></select></div><div class="field"><label>Priority</label><select id="remPriority"><option>low</option><option selected>normal</option><option>high</option><option>critical</option></select></div></div>
<div class="field"><label>Days</label><div class="checks" id="weekdayChecks"></div></div><div class="three"><div class="field"><label>Start</label><input id="remStart" type="time" value="14:00"></div><div class="field"><label>Stop</label><input id="remStop" type="time" value="18:00"></div><div class="field"><label>Repeat every, min</label><input id="remRepeat" type="number" min="1" value="30"></div></div>
<div class="two"><div><div class="field"><label>Timezone</label><input id="remTimezone" value="Asia/Qyzylorda"></div><label><input id="remChecklist" type="checkbox" checked> Checklist mode: notify pending only</label><label style="display:block;margin-top:8px"><input id="remUseRule" type="checkbox" checked> Use current visual condition</label></div><div><label style="font-size:13px;font-weight:700">Recipients</label><div id="remTargets" class="target-list"></div></div></div>
<hr><div class="section-title">Recurring pause</div><div class="row"><select id="pauseDay"><option value="">No pause</option><option value="mon">Monday</option><option value="tue">Tuesday</option><option value="wed">Wednesday</option><option value="thu">Thursday</option><option value="fri">Friday</option><option value="sat">Saturday</option><option value="sun">Sunday</option></select><input id="pauseStart" type="time" value="12:00"><input id="pauseEnd" type="time" value="13:00"></div><button class="btn primary" style="margin-top:14px" id="createReminder">Create reminder</button> <span id="remStatus"></span></div>
<div class="card"><table class="table"><thead><tr><th>Name</th><th>Priority</th><th>Schedule</th><th>Checklist</th><th>Status</th></tr></thead><tbody id="reminderRows"></tbody></table></div></section>

<section id="runs" class="view hidden"><div class="top"><div><div class="h1">Runs & checklist</div><div class="muted">Manual control over concrete reminder executions.</div></div><button class="btn" id="refreshRuns">Refresh</button></div><div class="card"><table class="table"><thead><tr><th>Reminder</th><th>Period</th><th>Status</th><th>Attempt</th><th>Pause</th><th>Actions</th></tr></thead><tbody id="runRows"></tbody></table></div><div id="checklistCard" class="card hidden"><div class="section-title">Checklist</div><div id="checklistRows"></div></div></section>

<section id="clients" class="view hidden"><div class="top"><div><div class="h1">Clients</div><div class="muted">Telegram recipients and optional Google Calendar identity.</div></div></div><div class="card"><div class="two"><div class="field"><label>Name</label><input id="clientName"></div><div class="field"><label>Telegram chat ID</label><input id="clientChat"></div><div class="field"><label>Telegram user ID (optional)</label><input id="clientUser"></div><div class="field"><label>Google Calendar ID (optional)</label><input id="clientCalendar"></div></div><button class="btn primary" id="addClient">Add client</button><table class="table" style="margin-top:14px"><tbody id="clientRows"></tbody></table></div></section>

<section id="templates" class="view hidden"><div class="top"><div><div class="h1">Message templates</div><div class="muted">Text, aliases and Telegram controls.</div></div></div><div class="card"><div class="field"><label>Name</label><input id="templateName" value="Timesheet reminder"></div><div class="field"><label>Message</label><textarea id="templateBody">Hi {{client.name}}!\n\nPlease complete your timesheet before {{deadline}}.\nRemaining: {{remaining_count}}.</textarea></div><div class="two"><div class="field"><label>Control type</label><select id="controlType"><option value="callback">Inline callback button</option><option value="url">URL button</option><option value="reply">Reply keyboard button</option><option value="command">Command</option><option value="request">Request contact/location</option></select></div><div class="field"><label>Control label</label><input id="controlLabel" value="Done"></div></div><button class="btn primary" id="saveTemplate">Save template</button><div id="templateList" class="muted" style="margin-top:12px"></div></div></section>

<section id="aliases" class="view hidden"><div class="top"><div><div class="h1">Aliases</div><div class="muted">Reusable values in messages and conditions.</div></div></div><div class="card"><div class="two"><input id="aliasKey" placeholder="timesheet_url"><input id="aliasValue" placeholder="https://..."></div><button class="btn primary" style="margin-top:12px" id="addAlias">Add alias</button><table class="table" style="margin-top:14px"><tbody id="aliasRows"></tbody></table></div></section>

<section id="conditions" class="view hidden"><div class="top"><div><div class="h1">Conditions builder</div><div class="muted">Nested AND/OR rules without code. The current rule can be attached to a reminder.</div></div><button class="btn primary" id="addCondition">+ Condition</button></div><div class="two"><div class="card"><div class="row"><b>WHEN</b><select id="rootOp"><option value="and">ALL (AND)</option><option value="or">ANY (OR)</option></select><button class="btn" id="addGroup">+ Group</button></div><div id="ruleTree"></div><hr><b>THEN</b><div class="field"><label>Action</label><select id="thenAction"><option value="send_message">Send message</option><option value="select_pending">Target pending checklist clients</option><option value="pause_run">Pause run</option><option value="stop_run">Stop run</option><option value="skip">Skip execution</option><option value="change_priority">Change priority</option><option value="webhook">Call webhook</option></select></div><button class="btn" id="validateRule">Validate</button> <span id="ruleStatus"></span></div><div class="card"><div class="tabs"><button class="active" data-tab="readable">Readable</button><button data-tab="json">JSON</button></div><div id="readable" class="preview"></div><pre id="json" class="preview hidden"></pre></div></div></section>

<section id="settings" class="view hidden"><div class="top"><div><div class="h1">Bot settings</div><div class="muted">Secrets belong to hosted environment settings.</div></div></div><div class="card"><p><b>Telegram webhook</b>: <code>/api/telegram/webhook</code></p><p><b>Scheduler</b>: <code>POST /api/cron/tick</code> with <code>Authorization: Bearer &lt;CRON_SECRET&gt;</code>.</p><p class="muted">Configure TELEGRAM_BOT_TOKEN, TELEGRAM_WEBHOOK_SECRET, CRON_SECRET and Google OAuth secrets. Google Calendar falls back to configured work hours when OAuth is absent.</p></div></section>
</main></div>
<script>
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const state={root:{type:'group',operator:'and',children:[{type:'condition',left:'checklist.pendingCount',operator:'gt',right:0},{type:'condition',left:'calendar.isWorkingTime',operator:'eq',right:true}]},clients:[],templates:[],runs:[]};
const sources=['checklist.pendingCount','checklist.doneCount','checklist.completionPercent','calendar.isWorkingDay','calendar.isWorkingTime','calendar.isBusy','system.currentTime','reminder.priority','reminder.attempt','client.tags','alias.custom'];
const ops=['eq','neq','gt','gte','lt','lte','contains','not_contains','in','not_in','empty','not_empty','before','after','between'];
const days=[['mon','Mon'],['tue','Tue'],['wed','Wed'],['thu','Thu'],['fri','Fri'],['sat','Sat'],['sun','Sun']];
function el(t,c=''){const e=document.createElement(t);e.className=c;return e}function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function removeNode(g,t){const i=g.children.indexOf(t);if(i>=0){g.children.splice(i,1);return true}for(const c of g.children)if(c.type==='group'&&removeNode(c,t))return true;return false}
function drawCondition(n,h){const r=el('div','rule row'),s=document.createElement('select'),o=document.createElement('select'),v=document.createElement('input'),d=el('button','btn');sources.forEach(x=>s.add(new Option(x,x,false,n.left===x)));ops.forEach(x=>o.add(new Option(x,x,false,n.operator===x)));v.value=Array.isArray(n.right)?n.right.join(','):String(n.right??'');s.onchange=()=>{n.left=s.value;renderPreview()};o.onchange=()=>{n.operator=o.value;renderPreview()};v.oninput=()=>{let x=v.value;if(x==='true'||x==='false')n.right=x==='true';else if(x!==''&&!Number.isNaN(Number(x)))n.right=Number(x);else n.right=x;renderPreview()};d.textContent='×';d.onclick=()=>{removeNode(state.root,n);renderRule()};r.append(s,o,v,d);h.append(r)}
function drawGroup(g,h,depth=0){const b=el('div','group'),head=el('div','row'),lab=el('b'),op=document.createElement('select');lab.textContent=depth?'GROUP':'ALL / ANY';['and','or'].forEach(x=>op.add(new Option(x.toUpperCase(),x,false,g.operator===x)));op.onchange=()=>{g.operator=op.value;renderRule()};head.append(lab,op);if(depth){const d=el('button','btn');d.textContent='Remove group';d.onclick=()=>{removeNode(state.root,g);renderRule()};head.append(d)}b.append(head);g.children.forEach(n=>n.type==='group'?drawGroup(n,b,depth+1):drawCondition(n,b));const a=el('button','btn'),ag=el('button','btn');a.textContent='+ condition';a.onclick=()=>{g.children.push({type:'condition',left:'checklist.pendingCount',operator:'gt',right:0});renderRule()};ag.textContent='+ group';ag.onclick=()=>{g.children.push({type:'group',operator:'and',children:[]});renderRule()};b.append(a,ag);h.append(b)}
function readable(n,d=0){if(n.type==='condition')return '  '.repeat(d)+'• '+n.left+' '+n.operator+' '+JSON.stringify(n.right);return '  '.repeat(d)+(n.operator==='and'?'ALL':'ANY')+'\n'+n.children.map(c=>readable(c,d+1)).join('\n')}
function currentRule(){return {condition:state.root,then:[{type:q('#thenAction').value}],else:[{type:'stop_run'}]}}
function renderPreview(){q('#readable').textContent=readable(state.root)+'\n\nTHEN\n  • '+q('#thenAction').value+'\nELSE\n  • stop_run';q('#json').textContent=JSON.stringify(currentRule(),null,2)}
function renderRule(){q('#ruleTree').innerHTML='';drawGroup(state.root,q('#ruleTree'));q('#rootOp').value=state.root.operator;renderPreview()}
function api(url,opt){return fetch(url,opt).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||r.statusText);return d})}
function renderTargets(){q('#remTargets').innerHTML=state.clients.length?state.clients.map(c=>'<label><input type="checkbox" class="targetCheck" value="'+esc(c.id)+'"> '+esc(c.display_name)+'</label>').join(''):'<span class="muted">Add clients first.</span>'}
function renderTemplates(){q('#remTemplate').innerHTML=state.templates.map(t=>'<option value="'+esc(t.id)+'">'+esc(t.name)+'</option>').join('');q('#templateList').textContent=state.templates.length?'Saved: '+state.templates.map(t=>t.name).join(', '):'No saved templates yet.'}
async function refresh(){
 const [d,rs,cs,as,ts,runs]=await Promise.all([api('/api/dashboard'),api('/api/reminders'),api('/api/clients'),api('/api/aliases'),api('/api/templates'),api('/api/runs')]);state.clients=cs;state.templates=ts;state.runs=runs;
 q('#statReminders').textContent=d.reminders;q('#statClients').textContent=d.clients;q('#statPending').textContent=d.pending;
 q('#reminderRows').innerHTML=rs.map(x=>{const s=JSON.parse(x.schedule_json);return '<tr><td>'+esc(x.name)+'</td><td><span class="pill">'+esc(x.priority)+'</span></td><td>'+esc((s.weekdays||[]).join(','))+' '+esc(s.startTime)+'–'+esc(s.stopTime)+' / '+esc(s.repeatEveryMinutes)+'m</td><td>'+(x.checklist_mode?'yes':'no')+'</td><td>'+(x.enabled?'on':'off')+'</td></tr>'}).join('');
 q('#clientRows').innerHTML=cs.map(x=>'<tr><td>'+esc(x.display_name)+'</td><td>'+esc(x.telegram_chat_id)+'</td><td>'+esc(x.calendar_id||'—')+'</td></tr>').join('');q('#aliasRows').innerHTML=as.map(x=>'<tr><td>{{'+esc(x.key)+'}}</td><td>'+esc(x.value)+'</td></tr>').join('');renderTargets();renderTemplates();renderRuns();
}
function renderRuns(){q('#runRows').innerHTML=state.runs.map(r=>'<tr><td><button class="btn openRun" data-id="'+esc(r.id)+'">'+esc(r.reminder_name)+'</button></td><td>'+esc(r.period_key)+'</td><td>'+esc(r.status)+'</td><td>'+esc(r.attempt)+'</td><td>'+esc(r.pause_until||'—')+'</td><td><button class="btn pauseRun" data-id="'+esc(r.id)+'">Pause 1h</button> <button class="btn resumeRun" data-id="'+esc(r.id)+'">Resume</button> <button class="btn danger stopRun" data-id="'+esc(r.id)+'">Stop</button></td></tr>').join('');qa('.openRun').forEach(b=>b.onclick=()=>openChecklist(b.dataset.id));qa('.pauseRun').forEach(b=>b.onclick=async()=>{await api('/api/runs/'+b.dataset.id+'/pause',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({until:new Date(Date.now()+3600000).toISOString()})});refresh()});qa('.resumeRun').forEach(b=>b.onclick=async()=>{await api('/api/runs/'+b.dataset.id+'/resume',{method:'POST'});refresh()});qa('.stopRun').forEach(b=>b.onclick=async()=>{await api('/api/runs/'+b.dataset.id+'/stop',{method:'POST'});refresh()})}
async function openChecklist(id){const items=await api('/api/runs/'+id+'/checklist');q('#checklistCard').classList.remove('hidden');q('#checklistRows').innerHTML=items.length?items.map(i=>'<div class="row rule"><b style="flex:1">'+esc(i.label)+'</b><span class="pill">'+esc(i.status)+'</span><button class="btn toggleItem" data-id="'+esc(i.id)+'">'+(i.status==='done'?'Mark pending':'Mark done')+'</button></div>').join(''):'<span class="muted">This run has no checklist.</span>';qa('.toggleItem').forEach(b=>b.onclick=async()=>{await api('/api/checklist/'+b.dataset.id+'/toggle',{method:'POST'});openChecklist(id);refresh()})}
q('#weekdayChecks').innerHTML=days.map(([v,l])=>'<label><input type="checkbox" class="weekday" value="'+v+'" '+(v==='fri'?'checked':'')+'> '+l+'</label>').join('');
qa('.side button').forEach(b=>b.onclick=()=>{qa('.side button').forEach(x=>x.classList.remove('active'));b.classList.add('active');qa('.view').forEach(x=>x.classList.add('hidden'));q('#'+b.dataset.view).classList.remove('hidden')});
q('#rootOp').onchange=e=>{state.root.operator=e.target.value;renderRule()};q('#addCondition').onclick=()=>{state.root.children.push({type:'condition',left:'reminder.attempt',operator:'gte',right:3});renderRule()};q('#addGroup').onclick=()=>{state.root.children.push({type:'group',operator:'or',children:[{type:'condition',left:'system.currentTime',operator:'gte',right:'15:00'}]});renderRule()};q('#thenAction').onchange=renderPreview;q('#validateRule').onclick=async()=>{try{const d=await api('/api/rules/validate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(currentRule())});q('#ruleStatus').textContent=d.valid?'Valid':d.errors.join(', ');q('#ruleStatus').className=d.valid?'ok':'bad'}catch(e){q('#ruleStatus').textContent=e.message;q('#ruleStatus').className='bad'}};qa('[data-tab]').forEach(b=>b.onclick=()=>{qa('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');['readable','json'].forEach(id=>q('#'+id).classList.toggle('hidden',id!==b.dataset.tab))});
q('#addClient').onclick=async()=>{await api('/api/clients',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({display_name:q('#clientName').value,telegram_chat_id:q('#clientChat').value,telegram_user_id:q('#clientUser').value||undefined,calendar_id:q('#clientCalendar').value||undefined})});['#clientName','#clientChat','#clientUser','#clientCalendar'].forEach(s=>q(s).value='');refresh()};
q('#addAlias').onclick=async()=>{await api('/api/aliases',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({key:q('#aliasKey').value,value:q('#aliasValue').value})});q('#aliasKey').value='';q('#aliasValue').value='';refresh()};
q('#saveTemplate').onclick=async()=>{await api('/api/templates',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:q('#templateName').value,body:q('#templateBody').value,controls:[{type:q('#controlType').value,label:q('#controlLabel').value}]})});refresh()};
q('#createReminder').onclick=async()=>{try{const weekdays=qa('.weekday:checked').map(x=>x.value),targetIds=qa('.targetCheck:checked').map(x=>x.value),pauseDay=q('#pauseDay').value;const payload={name:q('#remName').value,template_id:q('#remTemplate').value,priority:q('#remPriority').value,schedule:{kind:'weekly',weekdays,startTime:q('#remStart').value,stopTime:q('#remStop').value,repeatEveryMinutes:Number(q('#remRepeat').value),timezone:q('#remTimezone').value,workingStart:'09:00',workingEnd:'18:00'},pauseRules:pauseDay?[{weekdays:[pauseDay],startTime:q('#pauseStart').value,endTime:q('#pauseEnd').value}]:[],checklistMode:q('#remChecklist').checked,targetIds,conditionRule:q('#remUseRule').checked?currentRule():undefined};await api('/api/reminders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});q('#remStatus').textContent='Created';q('#remStatus').className='ok';refresh()}catch(e){q('#remStatus').textContent=e.message;q('#remStatus').className='bad'}};
q('#seedTimesheet').onclick=async()=>{const d=await api('/api/presets/timesheet',{method:'POST'});alert(d.message);refresh()};q('#refreshReminders').onclick=refresh;q('#refreshRuns').onclick=refresh;
renderRule();refresh().catch(e=>console.error(e));
</script></body></html>`;
